### ISSUE TITLE
Compose Bug

### ISSUE THREAD

**Issue by moonglum** [beastaugh/udon#3] opened 2011-04-07 08:53 UTC
I ran into the following errors when running the examples from the documentation (in Safari):

```
var ceilMax = Udon.compose([Math.ceil, Math.max], 2);

/* ceilmax is now:

function () {
            var a2 = a1.concat(Udon._slice.call(arguments, 0));
            if (a2.length < n) {
                a2.unshift(f);
                a1 = a2;
                return accumulator;
            } else {
                return f.apply(null, a2);
            }
        }
*/

ceilMax(0.7)(1.1);
/* -> TypeError: Result of expression 'ceilMax(0.7)' [NaN] is not a function. */

ceilMax(0.7);
/* -> NaN */
```

**Comment by beastaugh** [comment] 2011-04-08 15:50
Looks like this is the `ncurry` bug in a different guise—it should be fixed now. I'm adding a regression test.

**Closed as completed** 2011-04-08 22:24 UTC
